const API_URL="https://zikuzakuapi.sarmendiz.workers.dev/";
const TEAM_RULES={"EspaÃ±a":{api:["Spain"],win:21,draw:7},"Francia":{api:["France"],win:21,draw:7},"Argentina":{api:["Argentina"],win:21,draw:7},"Portugal":{api:["Portugal"],win:21,draw:7},"Inglaterra":{api:["England"],win:24,draw:8},"Brasil":{api:["Brazil"],win:24,draw:8},"Alemania":{api:["Germany"],win:24,draw:8},"PaÃ­ses Bajos":{api:["Netherlands"],win:24,draw:8},"Marruecos":{api:["Morocco"],win:27,draw:9},"BÃ©lgica":{api:["Belgium"],win:27,draw:9},"Croacia":{api:["Croatia"],win:27,draw:9},"Colombia":{api:["Colombia"],win:27,draw:9},"Noruega":{api:["Norway"],win:30,draw:10},"Uruguay":{api:["Uruguay"],win:30,draw:10},"Senegal":{api:["Senegal"],win:30,draw:10},"Suiza":{api:["Switzerland"],win:30,draw:10},"JapÃ³n":{api:["Japan"],win:33,draw:11},"USA":{api:["United States","USA"],win:33,draw:11},"Turquia":{api:["Turkey","TÃ¼rkiye"],win:33,draw:11},"Ecuador":{api:["Ecuador"],win:33,draw:11},"Austria":{api:["Austria"],win:36,draw:12},"Suecia":{api:["Sweden"],win:36,draw:12},"Paraguay":{api:["Paraguay"],win:36,draw:12},"MÃ©xico":{api:["Mexico"],win:36,draw:12},"Corea del Sur":{api:["South Korea","Korea Republic"],win:39,draw:13},"Escocia":{api:["Scotland"],win:39,draw:13},"Costa de Marfil":{api:["Ivory Coast","CÃ´te d'Ivoire"],win:39,draw:13},"CanadÃ¡":{api:["Canada"],win:39,draw:13},"Bosnia":{api:["Bosnia and Herzegovina"],win:42,draw:14},"Republica Checa":{api:["Czechia","Czech Republic"],win:42,draw:14},"Egipto":{api:["Egypt"],win:42,draw:14},"Ghana":{api:["Ghana"],win:42,draw:14},"Argelia":{api:["Algeria"],win:45,draw:15},"TÃºnez":{api:["Tunisia"],win:45,draw:15},"Australia":{api:["Australia"],win:45,draw:15},"Iran":{api:["Iran"],win:45,draw:15},"Arabia SaudÃ­":{api:["Saudi Arabia"],win:48,draw:16},"Qatar":{api:["Qatar"],win:48,draw:16},"RD Congo":{api:["DR Congo","Congo DR"],win:48,draw:16},"SudÃ¡frica":{api:["South Africa"],win:48,draw:16},"Nueva Zelanda":{api:["New Zealand"],win:51,draw:17},"UzbekistÃ¡n":{api:["Uzbekistan"],win:51,draw:17},"Cabo Verde":{api:["Cape Verde"],win:51,draw:17},"PanamÃ¡":{api:["Panama"],win:51,draw:17},"HaitÃ­":{api:["Haiti"],win:54,draw:18},"Curazao":{api:["Curacao","CuraÃ§ao"],win:54,draw:18},"Iraq":{api:["Iraq"],win:54,draw:18},"Jordania":{api:["Jordan"],win:54,draw:18}};
const ROUND_BONUS={LAST_32:5,ROUND_OF_32:5,LAST_16:10,ROUND_OF_16:10,QUARTER_FINALS:15,SEMI_FINALS:20,FINAL:40,THIRD_PLACE:10};
let players=[{name:"ALBA",points:0,img:"alba.png",shirt:"Escocia",number:7,animal:"BÃºho",bio:"Le gustan las galletitas de dinosaurios y el viento en su sÃ©ptimo piso.",teams:[["Argentina",0],["Inglaterra",0],["Colombia",0],["Suiza",0],["JapÃ³n",0],["Austria",0],["Escocia",0],["Egipto",0],["Australia",0],["RD Congo",0],["Curazao",0]]},{name:"MIKEL XABIER",points:0,img:"xabier.png",shirt:"Argentina",number:6,animal:"Capibara",bio:"Le gusta hablar con personas desconocidas y con personas de la tercera edad.",teams:[["Argentina",0],["Alemania",0],["Marruecos",0],["Noruega",0],["USA",0],["MÃ©xico",0],["Costa de Marfil",0],["Egipto",0],["Australia",0],["RD Congo",0],["Curazao",0]]},{name:"LEIRE",points:0,img:"leire.png",shirt:"EspaÃ±a",number:9,animal:"Pantera",bio:"Le gusta la Virgen del Pilar y la paloterapia.",teams:[["EspaÃ±a",0],["Alemania",0],["Colombia",0],["Noruega",0],["JapÃ³n",0],["MÃ©xico",0],["CanadÃ¡",0],["Ghana",0],["Iran",0],["SudÃ¡frica",0],["HaitÃ­",0]]},{name:"ITOITZ",points:0,img:"itoitz.png",shirt:"Francia",number:8,animal:"Border Collie",bio:"Le gusta la bici, el Excel y hacer dominadas.",teams:[["Francia",0],["Inglaterra",0],["Colombia",0],["Noruega",0],["USA",0],["MÃ©xico",0],["Corea del Sur",0],["Egipto",0],["Australia",0],["RD Congo",0],["Curazao",0]]},{name:"ANE",points:0,img:"ane.png",shirt:"MÃ©xico",number:12,animal:"Setter inglÃ©s",bio:"Le gustan las motos y los perros.",teams:[["EspaÃ±a",0],["Alemania",0],["Colombia",0],["Noruega",0],["USA",0],["MÃ©xico",0],["Corea del Sur",0],["Egipto",0],["Australia",0],["RD Congo",0],["Curazao",0]]},{name:"AITOR",points:0,img:"aitor.png",shirt:"Brasil",number:10,animal:"Sapo",bio:"DJ y residente en el Bukowski. FanÃ¡tico de Andoni Brun.",teams:[["EspaÃ±a",0],["Brasil",0],["Colombia",0],["Noruega",0],["USA",0],["Suecia",0],["CanadÃ¡",0],["Egipto",0],["Australia",0],["RD Congo",0],["Curazao",0]]}];
function normalizeName(n){return String(n||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
function teamMatchesPorraName(porra,api){const r=TEAM_RULES[porra];if(!r)return normalizeName(porra)===normalizeName(api);return r.api.some(a=>normalizeName(a)===normalizeName(api))}
function isFinished(m){return["FINISHED","AWARDED"].includes(m.status)}
function getWinnerName(m){const w=m?.score?.winner;if(w==="HOME_TEAM")return m.homeTeam?.name;if(w==="AWAY_TEAM")return m.awayTeam?.name;if(w==="DRAW")return"DRAW";return null}
function getTeamResult(m,t){const h=m.homeTeam?.name||"",a=m.awayTeam?.name||"",ph=teamMatchesPorraName(t,h),pa=teamMatchesPorraName(t,a);if(!ph&&!pa||!isFinished(m))return null;const w=getWinnerName(m);if(w==="DRAW")return"draw";if(ph&&w===h)return"win";if(pa&&w===a)return"win";return"loss"}
function getBonusForMatch(m,r){return r==="win"?(ROUND_BONUS[m.stage]||0):0}
function calculatePointsFromMatches(matches){players=players.map(p=>{let total=0;const teams=p.teams.map(([team])=>{const rule=TEAM_RULES[team]||{win:0,draw:0};let pts=0;matches.forEach(m=>{const r=getTeamResult(m,team);if(r==="win")pts+=rule.win+getBonusForMatch(m,r);if(r==="draw")pts+=rule.draw});total+=pts;return[team,pts]});return{...p,points:total,teams}})}
async function updateFromApi(){const status=document.getElementById("status");status.textContent="Consultando resultados oficiales del Mundial...";try{const res=await fetch(API_URL);const data=await res.json();if(!data.ok)throw new Error(data.message||"API sin datos");calculatePointsFromMatches(data.matches||[]);render();status.textContent="Puntos actualizados con resultados oficiales - "+new Date().toLocaleString("es-ES")}catch(e){console.error(e);status.textContent="No se han podido actualizar los resultados. Revisa el Worker o la conexiÃ³n."}}
function sortedPlayers(){return[...players].sort((a,b)=>b.points-a.points)}
function getRanks(o){let ranks=[],last=null,rank=0;o.forEach((p,i)=>{if(p.points!==last){rank=i+1;last=p.points}ranks.push(rank)});return ranks}
function medalClass(r){if(r===1)return"first";if(r===2)return"second";if(r===3)return"third";return""}
function medalText(r){return String(r)}
function render(){const ordered=sortedPlayers(),ranks=getRanks(ordered),leaders=ordered.filter(p=>p.points===ordered[0].points).map(p=>p.name).join(" y ");document.getElementById("leaderBanner").innerHTML=`<h2>Ahora va primero: <strong>${leaders}</strong></h2><div style="font-family:Arial,sans-serif;font-weight:900;color:#073967;">${ordered[0].points} puntos - reborde dorado activo</div>`;const ranking=document.getElementById("rankingBody");ranking.innerHTML="";ordered.forEach((p,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${medalText(ranks[i])}</td><td>${p.name}</td><td>${p.points}</td>`;ranking.appendChild(tr)});const cards=document.getElementById("cards");cards.innerHTML="";ordered.forEach((p,i)=>{const card=document.createElement("button");card.className="card "+medalClass(ranks[i]);card.onclick=()=>openFicha(p.name);card.innerHTML=`<div class="rank-badge">${medalText(ranks[i])}</div><img src="${p.img}" alt="${p.name}"><div class="points-tag">${p.points} pt</div>`;cards.appendChild(card)})}
function openFicha(name){const ordered=sortedPlayers(),ranks=getRanks(ordered),p=ordered.find(x=>x.name===name),i=ordered.findIndex(x=>x.name===name),active=p.teams.filter(t=>t[1]>0).length,best=[...p.teams].sort((a,b)=>b[1]-a[1])[0];document.getElementById("sheetImg").src=p.img;document.getElementById("sheetImg").alt=p.name;document.getElementById("sheetName").textContent=p.name;document.getElementById("sheetMeta").textContent=`${p.animal} - camiseta ${p.shirt} #${p.number}`;document.getElementById("sheetPoints").textContent=p.points;document.getElementById("bioTitle").textContent=`${p.name} - ${p.animal}`;document.getElementById("bioText").textContent=p.bio;document.getElementById("sheetRank").textContent=ranks[i];document.getElementById("sheetTeams").textContent=p.teams.length;document.getElementById("sheetActive").textContent=active;document.getElementById("sheetBest").textContent=best[1];const rows=document.getElementById("sheetScoreRows");rows.innerHTML="";p.teams.forEach(([team,pts])=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${team}</td><td>${pts}</td><td>${pts>0?"Ha sumado":"Pendiente"}</td>`;rows.appendChild(tr)});document.getElementById("modal").classList.add("active")}
function closeFicha(){document.getElementById("modal").classList.remove("active")}
render();updateFromApi();
let musicPlaying=false;
function startPorralab(){const intro=document.getElementById("intro"),audio=document.getElementById("himno");intro.classList.add("hidden");audio.play().then(()=>{musicPlaying=true;document.getElementById("musicToggle").textContent="Himno ON"}).catch(()=>{musicPlaying=false;document.getElementById("musicToggle").textContent="Himno OFF"})}
function toggleMusic(){const audio=document.getElementById("himno"),button=document.getElementById("musicToggle");if(audio.paused){audio.play().then(()=>{musicPlaying=true;button.textContent="Himno ON"}).catch(()=>{button.textContent="Himno OFF"})}else{audio.pause();musicPlaying=false;button.textContent="Himno OFF"}}
